# Generated by Django 6.0.4 on 2026-06-05 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(default='Admin', max_length=255)),
                ('category', models.CharField(default='Fitness', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('image_url', models.CharField(blank=True, help_text='Fallback static URL if no image uploaded, e.g., /img/blog/blog-1.jpg', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone_numbers', models.CharField(help_text='Comma-separated numbers, e.g., 125-711-811, 125-668-886', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('google_map_iframe_url', models.TextField(blank=True, help_text='Embed link for the map', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.CharField(blank=True, help_text='Fallback static URL if no image uploaded, e.g., /img/gallery/gallery-1.jpg', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(help_text='e.g., Month to Month, Single Class, Year Unlimited', max_length=100)),
                ('features', models.TextField(help_text='Comma-separated features, e.g., Free riding, Unlimited equipments, Personal trainer')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='e.g., flaticon-034-stationary-bike', max_length=100)),
                ('link', models.CharField(blank=True, default='#', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('image_url', models.CharField(blank=True, help_text='Fallback static URL if no image uploaded, e.g., /img/team/team-1.jpg', max_length=500, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(help_text='e.g., strength, cardio, group', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 60 mins', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='classes/')),
                ('image_url', models.CharField(blank=True, help_text='Fallback static URL if no image uploaded, e.g., /img/classes/class-1.jpg', max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainer')),
            ],
        ),
    ]
