# Generated by Django 6.1 on 2026-08-24 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_contactinfo_contactmessage_galleryitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='System', max_length=150)),
                ('action', models.CharField(help_text='e.g. ADMIN_CREATED_MEMBER, ADMIN_DELETED_CLASS', max_length=100)),
                ('entity', models.CharField(help_text='e.g. Member, Trainer, Class, Timetable, Plan', max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=60)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GymSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(default='GymLife Fitness Center', max_length=255)),
                ('tagline', models.CharField(blank=True, default='Shape Your Ideal Body With Elite Coaching', max_length=255, null=True)),
                ('contact_email', models.EmailField(default='support.gymcenter@gmail.com', max_length=254)),
                ('phone', models.CharField(default='125-711-811 / 125-668-886', max_length=100)),
                ('address', models.CharField(default='333 Middle Winchendon Rd, Rindge, NH 03461', max_length=500)),
                ('working_hours_weekday', models.CharField(default='Monday - Friday: 06:00 - 22:00', max_length=100)),
                ('working_hours_weekend', models.CharField(default='Saturday - Sunday: 07:00 - 20:00', max_length=100)),
                ('logo_url', models.CharField(blank=True, default='/img/logo.png', max_length=500, null=True)),
                ('google_map_url', models.TextField(blank=True, default='https://maps.google.com/maps?q=333%20Middle%20Winchendon%20Rd%2C%20Rindge%2C%20NH%2003461&t=&z=14&ie=UTF8&iwloc=&output=embed', null=True)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com', max_length=500, null=True)),
                ('twitter_url', models.URLField(blank=True, default='https://www.twitter.com', max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com', max_length=500, null=True)),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com', max_length=500, null=True)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('MEMBER_REGISTRATION', 'Member Registration'), ('CONTACT_ENQUIRY', 'Contact Enquiry'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_RECEIVED', 'Payment Received'), ('MEMBERSHIP_EXPIRING', 'Membership Expiring'), ('APPOINTMENT', 'Appointment'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=30)),
                ('link', models.CharField(default='/admin/dashboard', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classitem',
            name='capacity',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='classitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classitem',
            name='difficulty',
            field=models.CharField(choices=[('All Levels', 'All Levels'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='All Levels', max_length=50),
        ),
        migrations.AddField(
            model_name='classitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Drop-in price if applicable', max_digits=10),
        ),
        migrations.AddField(
            model_name='classitem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('READ', 'Read'), ('REPLIED', 'Replied'), ('ARCHIVED', 'Archived')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='General Inquiry', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='max_members',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='availability',
            field=models.CharField(blank=True, default='Mon - Sat (07:00 - 19:00)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience_years',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='qualification',
            field=models.CharField(blank=True, default='Certified Personal Trainer (CPT)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(blank=True, default='Fitness & Strength', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='GymLife Admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.CharField(blank=True, help_text='Fallback static URL, e.g. /img/blog/blog-1.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='classitem',
            name='category',
            field=models.CharField(help_text='e.g., STRENGTH, CARDIO, YOGA, BOXING, CROSSFIT', max_length=100),
        ),
        migrations.AlterField(
            model_name='classitem',
            name='duration',
            field=models.CharField(default='60 mins', help_text='e.g., 60 mins', max_length=100),
        ),
        migrations.AlterField(
            model_name='classitem',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='core.trainer'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image_url',
            field=models.CharField(blank=True, help_text='Fallback static URL, e.g., /img/gallery/gallery-1.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='features',
            field=models.TextField(help_text='Comma-separated or pipe-separated features'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='period',
            field=models.CharField(help_text='e.g., SINGLE PASS, 12 MONTHS UNLIMITED, 6 MONTHS ACCESS', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='flaticon-002-dumbell', help_text='e.g., flaticon-034-stationary-bike', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='role',
            field=models.CharField(help_text='e.g. Strength Coach, Yoga Master', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='twitter_url',
            field=models.URLField(blank=True, default='https://twitter.com', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://youtube.com', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('STAFF', 'Staff Member')], default='ADMIN', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('avatar_url', models.CharField(blank=True, default='/img/team/team-1.jpg', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('start_time', models.CharField(help_text='e.g. 06:00 or 6.00am', max_length=20)),
                ('end_time', models.CharField(help_text='e.g. 08:00 or 8.00am', max_length=20)),
                ('room', models.CharField(default='Main Gym Studio', help_text='e.g. Studio A, Boxing Arena, Yoga Hall', max_length=100)),
                ('capacity', models.IntegerField(default=25)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.classitem')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.trainer')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=25)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Name & Phone', max_length=255, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('profile_photo_url', models.CharField(blank=True, default='/img/team/team-1.jpg', max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue')], default='PAID', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.pricingplan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-join_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI / Google Pay', 'UPI / Google Pay'), ('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Online Gateway', 'Online Gateway')], default='Credit Card', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PAID', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.member')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.pricingplan')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
