# Generated by Django 6.1 on 2026-08-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_gymsettings_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(blank=True, db_index=True, help_text='Format: GYM-YYYY-NNNN', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('service', models.CharField(help_text='e.g. Modern Equipment, Personal Training Assessment', max_length=150)),
                ('scheduled_time', models.DateTimeField()),
                ('location', models.CharField(default='GymLife Arena (333 Middle Winchendon Rd)', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed & Scheduled'), ('PENDING', 'Pending Confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=30)),
                ('email_delivered', models.BooleanField(default=False)),
                ('sms_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
