# Generated by Django 6.1 on 2026-09-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_cancellation_reason_booking_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymsettings',
            name='smtp_from_email',
            field=models.CharField(blank=True, default='GymLife Fitness Arena <support.gymcenter@gmail.com>', max_length=255),
        ),
        migrations.AddField(
            model_name='gymsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='gymsettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gymsettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='gymsettings',
            name='smtp_provider',
            field=models.CharField(blank=True, default='GMAIL', max_length=50),
        ),
        migrations.AddField(
            model_name='gymsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gymsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gymsettings',
            name='smtp_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gymsettings',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=10),
        ),
    ]
