# Generated by Django 6.1 on 2026-08-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_booking_cancellation_reason_booking_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('notification_type', models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOOKING_CANCELLATION', 'Booking Cancellation'), ('BOOKING_RESCHEDULED', 'Booking Rescheduled'), ('BOOKING_REMINDER', 'Booking Reminder')], default='BOOKING_CONFIRMATION', max_length=40)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=20)),
                ('recipient', models.CharField(help_text='Email address or normalized phone number', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=20)),
                ('provider', models.CharField(choices=[('BREVO_SMTP', 'Brevo SMTP'), ('FAST2SMS', 'Fast2SMS API'), ('TWILIO', 'Twilio SMS'), ('WA_ME', 'WhatsApp Click-to-Chat')], default='BREVO_SMTP', max_length=30)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('appointment', models.ForeignKey(blank=True, help_text='Linked booking/appointment record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.booking')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['appointment', 'notification_type', 'channel', 'status'], name='notificatio_appoint_df972c_idx'), models.Index(fields=['created_at'], name='notificatio_created_01830a_idx')],
            },
        ),
    ]
